[project]
name = "vocal-analyzer"
version = "0.1.0"
description = "A tool to analyze vocals from audio files"
readme = "README.md"
requires-python = ">3.8,<=3.9"
dependencies = ["spleeter", "librosa", "openai", "matplotlib", "numpy"]

[project.scripts]
va = "vocal_analyzer.main:main"
